version: '3'

services:
  mongodbsomaiya:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /root/mongo/database:/data/db

  mongodbdjs:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - /root/mongo/databasedjs:/data/db
      
  mongodbapp:
    image: mongo
    ports:
      - 27019:27017
    volumes:
      - /root/mongo/databaseapp:/data/db

